services:
  streamingpro:
    build: 
      context: .
      dockerfile: Dockerfile
      target: deps # Solo construimos hasta la etapa de deps para desarrollo
    container_name: streamingpro-dev
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npm run dev"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - streaming_network
    depends_on:
      - streamingpro-backend

  streamingpro-backend:
    image: datarhei/core:latest
    container_name: streamingpro-backend-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
      - "1935:1935"
      - "6000:6000/udp"
    environment:
      - CORE_API_AUTH_ENABLE=true
      - CORE_API_AUTH_USERNAME=admin
      - CORE_API_AUTH_PASSWORD=sincros2808
      - CORE_RTMP_ENABLE=true
      - CORE_RTMP_ADDRESS=:1935
      - CORE_SRT_ENABLE=true
      - CORE_SRT_ADDRESS=:6000
      - CORE_METRICS_ENABLE=true
      - CORE_SESSIONS_ENABLE=true
      - CORE_SESSIONS_PERSIST=true
    volumes:
      - core_config_dev:/core/config
      - core_data_dev:/core/data
    networks:
      - streaming_network

volumes:
  core_config_dev:
  core_data_dev:

networks:
  streaming_network:
    name: streaming_network_dev
    driver: bridge 